#wallpaper {
#	preload = /home/pnix/.Wallpapers/wallpapers/wall.png
#	path = /home/pnix/.Wallpapers/wallpapers/wall.png
#	spalsh = false
#}
preload = /home/pnix/.Wallpapers/wallpapers/wall.png
##wallpaper = eDP-1, /home/pnix/.Wallpapers/wallpapers/wall.png
wallpaper = DP-2, /home/pnix/.Wallpapers/wallpapers/wall.png
splash = false
